In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim) #0 dimensions
#
# Tensors are created using torch.tensor
# Vector 
vector = torch.tensor([7,7])
print(vector)

tensor(7)
0
tensor([7, 7])


In [8]:
# matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
# create random tensor
ran_ten = torch.rand(3,5)
ran_ten

tensor([[0.0411, 0.3769, 0.3567, 0.4726, 0.7039],
        [0.7722, 0.6397, 0.0887, 0.4856, 0.7257],
        [0.9839, 0.6905, 0.8456, 0.0565, 0.8509]])

In [18]:
#create randome tensor with similar shape to image tensor
random_image_T = torch.rand(224,224,3) #height, width, colour channels (R,G,B)
random_image_T.shape, random_image_T.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
#Zeros and ones 
#T of all Zeros
zero = torch.zeros(3,5)
zero*ran_ten
#T of all ones
one = torch.ones(3,5)
one

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [23]:
one_to_ten = torch.arange(start=1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#Creating like tensors 
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Tensor DataTypes 
float_32_tensor = torch.tensor([3.0,6.0,9.0],      
                               dtype = None,        #datatype
                               device = None,       #
                               requires_grad = False)
float_32_tensor

# Note- 3 big common errors in deep learning 
# 1 - Tensors not right datatype ( use tensor.dtype)
# 2 - Tensors not right shape ( use tensor.shape)
# 3 - Tensors not on right device (use tensor.device)

tensor([3., 6., 9.])

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
sometensor = torch.rand(3,4)
sometensor

tensor([[0.0281, 0.9105, 0.3065, 0.9984],
        [0.6284, 0.7747, 0.5968, 0.8358],
        [0.8870, 0.0681, 0.5782, 0.5963]])

In [31]:
#find out details
print(sometensor)
print(f"datatype is {sometensor.dtype}")
print(f"shape of tensor is {sometensor.shape}")
print(f"device of tensor is {sometensor.device}")

tensor([[0.0281, 0.9105, 0.3065, 0.9984],
        [0.6284, 0.7747, 0.5968, 0.8358],
        [0.8870, 0.0681, 0.5782, 0.5963]])
datatype is torch.float32
shape of tensor is torch.Size([3, 4])
device of tensor is cpu


In [ ]:
# Tensor operations: Add, subtract,multiply,division, matrix multiplication
tens = torch.tensor([1,2,3])

tens/10

tensor([0.1000, 0.2000, 0.3000])

In [38]:
# Matrix multiplication
test = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]]) # a matrix where each [] is a row so test = [1 2 3]
test1 = torch.tensor([[[2,5,3],[4,-3,6],[-7,8,9]]])                                      #   [4 5 6] 
torch.matmul(test,test1)                                                                 #   [7 8 9]

tensor([[[-11,  23,  42],
         [-14,  53,  96],
         [-17,  83, 150]]])

In [39]:
#Transpose
test.T

tensor([[[1],
         [4],
         [7]],

        [[2],
         [5],
         [8]],

        [[3],
         [6],
         [9]]])

In [40]:
# find min, max, mean, sum
x = torch.arange(0,100,10)
min(x)


tensor(0)

In [41]:
max(x)

tensor(90)

In [42]:
x.sum()

tensor(450)